# Generated by Django 4.1.3 on 2022-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='address',
            field=models.CharField(default='abcfdshgfggfd', max_length=100),
        ),
    ]
